version: "3"

services:
        mysql:
                image: mysql
                ports:
                        - 3307:3306
                environment:
                        - MYSQL_ROOT_PASSWORD=root
                        - MYSQL_DATABASE=mydb
        setup:
                build: ./setup
                volumes:
                        - ./setup:/usr/src/app
                depends_on:
                        - mysql
        api:
                build: ./API
                volumes:
                        - ./API:/usr/src/app
                ports:
                        - 5000:5000
                depends_on:
                        - mysql
                        - setup
        nginx:
                image: nginx:1.13.7
                ports:
                        - 80:80
                volumes: 
                        - ./nginx.conf:/etc/nginx/conf.d/default.conf
                depends_on:
                        - api
        
        